---
title: "Project Milestone 3"
author: "Yahan Chen"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(ggplot2)
library(scales)
library(patchwork)
```

## Data Cleaning

```{r}
mortality <- read.csv("https://github.com/AndreaChen0301/stat436/raw/main/mortality_ph2.5.csv")%>%
  rename_at(vars(starts_with('X')), funs(sub("X", "", .))) %>% 
  pivot_longer(!Country, names_to = "Year", values_to = "prematured_death")

welfare.percent <- read.csv("https://github.com/AndreaChen0301/stat436/raw/main/percent_welfare.csv")%>%
  rename_at(vars(starts_with('X')), funs(sub("X", "", .))) %>% 
  pivot_longer(!Country, names_to = "Year", values_to = "cost_percent")

mortality_per <- read.csv("https://github.com/AndreaChen0301/stat436/raw/main/mortality_per_mili.csv") %>%
  rename_at(vars(starts_with('X')), funs(sub("X", "", .))) %>% 
  pivot_longer(!Country, names_to = "Year", values_to = "death_per_million")

# health = right_join(welfare.percent, mortality, c("Country", "Year")) %>%
#   mutate(Year = as.numeric(Year))

health2 = right_join(welfare.percent, mortality_per, c("Country", "Year")) %>%
  mutate(Year = as.numeric(Year))

# write.csv(health, "../data/mortality_welfare", row.names=FALSE)
```

```{r}
# countries with all 31 years of records, align with policy stringency index records

complete.country = read.csv("https://github.com/AndreaChen0301/stat436/raw/main/co_emmit.csv") %>%
  group_by(Country) %>%
  mutate(nyear = n()) %>%
  filter(nyear==31) %>%
  pull(Country) %>%
  unique()
complete.country
```

## Visulizations

### Premature Deaths Barplot:

```{r, fig.height=5, fig.width=11}
# % welfare cost on premature death (PM) out of total welfare cost on premature death + premature deaths line plot

# Based on the number of premature death, we pick the top 10 countries with most premature death to see 
# the percent of welfare cost of premature death caused by PM within welfare on all premature death.

# premature death bar plot
mortality = health2 %>%
  filter(Country %in% complete.country) %>%
  mutate(Year = as.character(Year)) %>%
  filter(Year == "1990"| Year == "2019")
# 
# top.10 = mortality %>%
#   group_by(Country) %>%
#   summarise(death = mean(prematured_death))%>%
#   arrange(desc(death))%>%
#   slice_head(n=10)%>%
#   pull(Country)

mortality %>%
  filter(Country %in% per_top.10) %>%
  ggplot(aes(x=reorder(Country, death_per_million), y=death_per_million, fill = Year))+
  scale_fill_manual(values=c("#D95F02", "#1B9E77"))+
  geom_col(position="dodge", width=0.7)+
  geom_text(aes(label=death_per_million), position=position_dodge(width=0.75), hjust=0.4, vjust=-0.65, size=3)+
  scale_y_continuous(expand = c(0, 0, 0.1, 0.1))+
  labs(x="Country", y="Premature Death per Million", title = "Top 10 Countries with Most Premature Death Per Million Inhabitant Caused by PM in 1990 and 2019")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank())
```

### Percent of Welfare Cost on Premature Deaths caused by PM in Total Welfare Cost on Premature Death:
#### Compare its trend with premature deaths

```{r, fig.width=14, fig.height=10}
per_top.10 = mortality_per %>%
  filter(Country %in% complete.country) %>%
  group_by(Country) %>%
  summarise(death = mean(death_per_million))%>%
  arrange(desc(death))%>%
  slice_head(n=10)%>%
  pull(Country)

p = list()

p[["percent.plot"]] = health2 %>%
  filter(Country %in% per_top.10) %>%
  ggplot(aes(x=Year)) +
  geom_line(aes(y=cost_percent), color = "darkgreen", size=1.2)+
  facet_grid(reorder(Country, -death_per_million)~.)+
  labs(x="Year", y="Percent of Welfare Cost", title="Percent of Cost on Premature Death of Total Welfare Cost from 1990-2019")+
  theme_bw()+
  theme(strip.text.y = element_text(angle = 0))

p[["death.plot"]] = health2 %>%
  filter(Country %in% per_top.10) %>%
  ggplot(aes(x=Year)) +
  geom_line(aes(y=death_per_million), color = "steelblue4", size=1.2)+
  facet_grid(reorder(Country, -death_per_million)~.)+
  labs(x="Year", y="Premature Death per Million", title="Premature Death per Million Inhabitants Caused by PM from 1990-2019")+
  theme_bw()+
  theme(strip.text.y = element_text(angle = 0))

p[["percent.plot"]] + p[["death.plot"]]
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
